print("SIMPLE CALCULATOR")
num1 = float (input("Enter your first number"))
num2 = float(input("Enter your second number"))
print("/n")
print("Addition :", num1 + num2)
print("Subtraction :", num1 - num2)
print("Multiplication :", num1*num2)
print("Division :",num1/num2)